Practice branch
Swirastlynn/yet-another-weather-app pull request #1
Opened 2023-05-09 12:37 UTC by damianololo

my proposal current_weather_page UI

2023-05-10 08:43 UTC, Swirastlynn requested changes
you should extract more widgets, and refactor of a Stack is probably a good idea

2023-05-10 08:43 UTC, Swirastlynn commented on lib/weather/presentation/current_weather_page.dart
> +                onPressed: () => {}, icon: const Icon(Icons.density_medium))
trailing coma `),)` then reformat

2023-05-10 08:43 UTC, Swirastlynn commented on lib/weather/presentation/current_weather_page.dart
> +                          alignment: const Alignment(1, 0.1),
I didn't observe any impact of the Alignment on UI

2023-05-10 08:43 UTC, Swirastlynn commented on lib/weather/presentation/current_weather_page_components/small_table_stats.dart
> +  CurrentWeatherModel item;
You don't need to pass whole the object. You only use `humidity` so this is enough. It's a common mistake, which often creates spaghetti code in big projects (I experienced it hard, don't recommend)

Make it `final` please! It's inside a statelesswidget. You also can tell me in PM why final :)

2023-05-10 09:09 UTC, damianololo commented on lib/weather/presentation/current_weather_page.dart
> +                          alignment: const Alignment(1, 0.1),
removing unnecessary code

2023-05-10 09:14 UTC, damianololo commented on lib/weather/presentation/current_weather_page_components/small_table_stats.dart
> +  CurrentWeatherModel item;
I use humidity and windSpeed. Also I should use precipitation but i didn't see the precipitation property in the model

2023-05-16 08:46 UTC, Swirastlynn requested changes
My review may look like there's a lot of things to do yet, but this is the most important Code Review I have done since some time. Fixing it will teach you a lot.

2023-05-16 08:46 UTC, Swirastlynn commented on lib/weather/presentation/current_weather_page.dart
>      // FIXME: UI layer. The task is to change this to a more appropriate widget.
remove this line

2023-05-16 08:46 UTC, Swirastlynn commented on lib/weather/presentation/current_weather_page_components/main_stats_view.dart
> +  final CloudCalculator cloudCalculator = CloudCalculator();
1. 
```
  final DateTimeHelper dateTimeHelper = DateTimeHelper();
  final WindCalculator windCalculator = WindCalculator();
  final CloudCalculator cloudCalculator = CloudCalculator();
```
These 3 lines of code should be injected. 

By applying dependency injection, you could pass instances of the abstractions into the MainStatsView class through its constructor, allowing for better decoupling and testability. This way, the MainStatsView class can work with any implementation of the abstractions, promoting more modular and maintainable code.

2. Actually classes like DateTimeHelper, WindCalculator and CloudCalculator are not part of widgets. They are typical business logic, so they should be hidden from widgets. I'd rather use values calculated by them in the widget constructor. And not even care about dependency injection here. Rather somewhere they come from.

2023-05-16 08:46 UTC, Swirastlynn commented on lib/weather/presentation/current_weather_page_components/main_stats_view.dart
> +  final CloudCalculator cloudCalculator = CloudCalculator();
3. DateTimeHelper etc are actually utility classes. In Dart there's no need for Utility classes like in Java (or probably C#). Use global function usually, extension method from time to time.

2023-05-16 08:46 UTC, Swirastlynn commented on lib/weather/presentation/current_weather_page_components/main_stats_view.dart
> +  final CloudCalculator cloudCalculator = CloudCalculator();
4.
Actually, the clean solution is to use global functions for transforming cloudiness, windRating and other abstract values to String. How?

Introduce new Model named (for instance) CurrentWeatherPresentationModel. 
```
  final String formattedDateTime;
  final String iconCode;
  final String temperature;
  final String pressure;
  final String humidity;
  final String windSpeed;
  final String cloudiness;
```
This should be sent from Controller to Widget. 
What should be sent from UseCase to the Controller? CurrentWeatherModel. Transformations should be done in Controller.

2023-05-16 08:46 UTC, Swirastlynn commented on lib/weather/presentation/current_weather_page_components/small_table_stats.dart
> +  final double? windSpeed;
There should be Strings there, not abstract values. 
This line of code `pressure?.toString() ?? "empty",` is part of business logic.

2023-07-09 17:21 UTC, closed without merging